import 'package:thlaby3_save_editor/save/enums/skills/focus_reaction.dart';
import 'package:thlaby3_save_editor/save/enums/skills/skill.dart';
import 'package:thlaby3_save_editor/save/enums/skills/training.dart';
import 'package:thlaby3_save_editor/save/enums/skills/unique.dart';
import 'package:thlaby3_save_editor/save/enums/spells/reimu.dart';
import 'package:thlaby3_save_editor/save/enums/spells/renko.dart';
import 'package:thlaby3_save_editor/save/skill_tree.dart';

/// The characters in the game and the static data relating to their in-game
/// attributes
enum Character {
  reimu(
    <Mastery>[Mastery.mythical, Mastery.divine, Mastery.arcane],
    <Personality>[
      Personality.prodigy,
      Personality.freeSpirited,
      Personality.facilitator,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{
        1: yinYangOrb,
        2: PassiveSkill.hakureiProtection,
        5: barrierTalisman,
        7: recoveryTalisman,
      },
      LevelGate.second: <int, UniqueSkill>{
        0: armoredYinYangOrb,
        1: yinYangOrbParAffix,
        4: youkaiBuster,
        5: reimuPrivileges,
        6: barrierTalisman2,
        7: recoveryTalisman2,
        8: persuasionNeedle,
        10: focusedRecitation,
      },
      LevelGate.third: <int, UniqueSkill>{
        0: armoredYinYangOrb2,
        1: yinYangOrbPow,
        2: PassiveSkill.hakureiProtection2,
        5: greatHakureiBarrier,
        6: hakureiTalisman,
        7: flashExorcismBarrier,
      },
      LevelGate.fourth: <int, UniqueSkill>{
        2: PassiveSkill.hakureiProtection3,
        4: youkaiBuster2,
        5: reimuPrivileges2,
        6: greatHakureiBarrierTurn,
        8: persuasionNeedleMultiplier,
        9: dreamSeal,
        11: finalPrayer,
      },
      LevelGate.fifth: <int, UniqueSkill>{
        0: armoredYinYangOrbBoost,
        1: yinYangOrbDelay,
        2: PassiveSkill.hakureiProtectionRange,
        3: youkaiBusterShield,
        5: greatHakureiBarrierSelfProtect,
        6: greatHakureiBarrierRegen,
        7: flashExorcismBarrierDelay,
        8: persuasionNeedleGuard,
        10: finalPrayer2,
      },
      LevelGate.sixth: <int, UniqueSkill>{
        0: yinYangOrbParBoost,
        4: reimuPrivilegesPerm,
        5: reimuPrivilegesShare,
        7: flashExorcismBarrierTurn,
        8: persuasionNeedleHpDrain,
        9: dreamSealTurn,
        10: dreamSealDamageAmplifier,
        11: finalPrayerRange,
      },
      LevelGate.seventh: <int, UniqueSkill>{
        0: yinYangOrbDelay2,
        1: yinYangOrbCooldownPow,
        3: PassiveSkill.turnCounterPreservation,
        6: flashExorcismBarrierDamageTaken,
        7: greatHakureiBarrierRegen2,
      },
      LevelGate.eighth: <int, UniqueSkill>{
        4: PassiveSkill.turnCounterPreservation2,
        6: flashExorcismBarrierDamageTaken2,
        11: trueFinalPrayer,
      },
    },
  ),
  renko(
    <Mastery>[Mastery.cultural, Mastery.madness, Mastery.engineering],
    <Personality>[
      Personality.facilitator,
      Personality.brainy,
      Personality.altruistic,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{
        2: eagerSupport,
        3: readingStars,
        4: firstAid,
      },
      LevelGate.second: <int, UniqueSkill>{
        0: warningBeacon,
        1: PassiveSkill.beaconSpecialist,
        2: signalBeacon,
        5: knowledgeStrangeStrings,
      },
      LevelGate.third: <int, UniqueSkill>{
        0: swiftBeacon,
        1: targetBeacon,
        2: eagerSupportMentalCare,
        4: firstAidTraining,
        5: maryShield,
      },
      LevelGate.fourth: <int, UniqueSkill>{
        0: warningBeacon2,
        1: adeptBeaconSpecialist,
        2: signalBeacon2,
        3: abilityReadStars,
        4: abilityReadMoon,
        5: knowledgeStrangeStrings2,
        7: PassiveSkill.learningListExpansion1,
        8: firCldDamage,
        9: wndNtrDamage,
        10: mysSpiDamage,
        11: drkPhyDamage,
      },
      LevelGate.fifth: <int, UniqueSkill>{
        0: swiftBeacon2,
        1: targetBeacon2,
        2: eagerSupportSelfCare,
        4: PassiveSkill.firstAidEmergencySmoke,
        5: maryKnight,
        8: directDamage,
        10: magicDamage,
      },
      LevelGate.sixth: <int, UniqueSkill>{
        1: assaultBeacon,
        3: eagerSupportDevotedHeart,
        4: skillfulTreatment,
        5: knowledgeStrangeStringsShield,
        7: PassiveSkill.learningListExpansion2,
        8: firCldDamage2,
        9: wndNtrDamage2,
        10: mysSpiDamage2,
        11: drkPhyDamage2,
      },
      LevelGate.seventh: <int, UniqueSkill>{
        0: assaultBeaconTurnGauge,
        1: assaultBeaconTurnConversion,
        3: celestialStasis,
        8: ailmentBoost,
        10: buffDebuffBoost,
      },
      LevelGate.eighth: <int, UniqueSkill>{
        0: assaultBeacon2,
        2: assaultBeaconHpLoss,
        3: celestialStasisTurnGauge,
        4: celestialStasisTurnConversion,
        7: PassiveSkill.learningListExpansion3,
        8: directDamage2,
        9: PassiveSkill.learningCooldown,
        10: PassiveSkill.learningMpCost,
        11: magicDamage2,
      },
    },
  ),
  maribel(
    <Mastery>[Mastery.cultural, Mastery.divine, Mastery.arcane],
    <Personality>[
      Personality.upfront,
      Personality.airheaded,
      Personality.innerFacing,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.hazyBarrierDefense,
        3: UncategorizedUniqueSkill.hazyBarrierAttack,
        5: UncategorizedUniqueSkill.relativePsychology,
      },
      LevelGate.second: <int, UniqueSkill>{
        2: UncategorizedUniqueSkill.noviceBarrier,
        3: UncategorizedUniqueSkill.disorderlyBarrier,
        4: UncategorizedUniqueSkill.hazyBarrierAttackLucidification,
        5: UncategorizedUniqueSkill.boundaryManipulation,
      },
      LevelGate.third: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.noviceBarrierRecovery,
        2: UncategorizedUniqueSkill.noviceBarrier2,
        3: UncategorizedUniqueSkill.disorderlyBarrierThirdLayer,
        4: UncategorizedUniqueSkill.boundaryAnchoring,
        5: UncategorizedUniqueSkill.abilitySeeBarriers,
        6: UncategorizedUniqueSkill.relativePsychologySecrets,
        7: UncategorizedUniqueSkill.abilityUnbridled,
        8: quickCharge,
        9: UncategorizedUniqueSkill.renkosEyes,
      },
      LevelGate.fourth: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.noviceBarrierRecovery2,
        2: UncategorizedUniqueSkill.noviceBarrier3,
        4: UncategorizedUniqueSkill.hazyBarrierAttackSpi,
        5: UncategorizedUniqueSkill.overflowingAnomalousPower,
        6: UncategorizedUniqueSkill.abilityFiddleBarriers,
        8: UncategorizedUniqueSkill.abilityUnbridledGuardPierce,
      },
      LevelGate.fifth: <int, UniqueSkill>{
        2: UncategorizedUniqueSkill.chaosBarrier,
        3: UncategorizedUniqueSkill.disorderlyBarrierFourthLayer,
        4: UncategorizedUniqueSkill.hazyBuffAbsorption,
        5: UncategorizedUniqueSkill.abilityUnderstandBoundaries,
        6: UncategorizedUniqueSkill.relativePsychologyMastery,
        7: UncategorizedUniqueSkill.abilityUnbridledPowerControl,
        8: focusedRecitation,
      },
      LevelGate.sixth: <int, UniqueSkill>{
        3: UncategorizedUniqueSkill.chaosBarrierBoundary,
        4: UncategorizedUniqueSkill.hazyMoonBarrier,
        5: UncategorizedUniqueSkill.overflowingAnomalousPowerAnomaly,
        8: UncategorizedUniqueSkill.abilityUnbridledGuardPierce2,
        9: quickCharge2,
      },
      LevelGate.seventh: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.noviceBarrierKnowledge,
        2: UncategorizedUniqueSkill.chaosBarrierDoubleBoost,
        3: UncategorizedUniqueSkill.disorderlyBarrierExpansion,
        6: UncategorizedUniqueSkill.boundaryFantasyReality,
        7: UncategorizedUniqueSkill.abilityUnbridledPowerDevelopment,
        9: UncategorizedUniqueSkill.renkosPartner,
      },
      LevelGate.eighth: <int, UniqueSkill>{
        4: UncategorizedUniqueSkill.maryMagician,
        5: UncategorizedUniqueSkill.overflowingAnomalousPowerFearsome,
        6: UncategorizedUniqueSkill.overflowingAnomalousPowerBudding,
        7: UncategorizedUniqueSkill.abilityUnbridledPowerAwakening,
        9: UncategorizedUniqueSkill.allEncompassingGuardPierce,
      },
    },
    additionalSkillRequirements: <UniqueSkill, List<Skill>>{
      focusedRecitation: <Skill>[quickCharge],
    },
  ),
  meiling(
    <Mastery>[Mastery.vigor, Mastery.botanical, Mastery.heavy],
    <Personality>[
      Personality.laborer,
      Personality.easygoing,
      Personality.sturdy,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{
        0: UncategorizedUniqueSkill.blossomingLightOrb,
        2: UncategorizedUniqueSkill.combo,
        6: UncategorizedUniqueSkill.restorativeQigong,
        8: UncategorizedUniqueSkill.focusedGuard,
        9: UncategorizedUniqueSkill.bondsScarletDevilMansion,
      },
      LevelGate.second: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.qiCrestBlossomingLightOrb,
        2: UncategorizedUniqueSkill.combo2,
        3: UncategorizedUniqueSkill.mountainBreakingCannon,
        5: UncategorizedUniqueSkill.qigongEnvelopment,
        6: UncategorizedUniqueSkill.restorativeQigongAilmentRecovery,
        7: UncategorizedUniqueSkill.colorfulRain,
        8: UncategorizedUniqueSkill.initialQigongGain,
        9: UncategorizedUniqueSkill.gatekeepersDuty,
      },
      LevelGate.third: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.qiCrestBlossomingLightOrbQigongGain,
        2: UncategorizedUniqueSkill.directAttackCounter,
        3: UncategorizedUniqueSkill.mountainBreakingCannonQigongGain,
        4: UncategorizedUniqueSkill.painToQigong,
        5: UncategorizedUniqueSkill.qigongToStats,
        6: UncategorizedUniqueSkill.parSlay,
        7: UncategorizedUniqueSkill.colorfulRainQigongGain,
      },
      LevelGate.fourth: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.qiCrestBlossomingLightOrbParAffix,
        2: UncategorizedUniqueSkill.qiCrestStarPulseShot,
        3: UncategorizedUniqueSkill.mountainBreakingCannon2,
        4: UncategorizedUniqueSkill.qiCrestMountainBreakingCannon,
        5: UncategorizedUniqueSkill.qigongEnvelopment2,
        6: UncategorizedUniqueSkill.qigongFromParFoes,
        7: UncategorizedUniqueSkill.parRemovalDown,
        8: UncategorizedUniqueSkill.initialQigongGain2,
      },
      LevelGate.fifth: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.qiCrestBlossomingLightOrb2,
        2: UncategorizedUniqueSkill.directAttackCounter2,
        3: UncategorizedUniqueSkill.mountainBreakingCannonDelay,
        4: UncategorizedUniqueSkill.painToQigong2,
        6: UncategorizedUniqueSkill.parSlay2,
        7: UncategorizedUniqueSkill.colorfulRainQigongRecoveryUp,
        8: UncategorizedUniqueSkill.focusedGuard2,
        9: UncategorizedUniqueSkill.bondsScarletDevilMansion2,
      },
      LevelGate.sixth: <int, UniqueSkill>{
        1: UncategorizedUniqueSkill.qiCrestBlossomingLightOrbParBoost,
        2: UncategorizedUniqueSkill.qiCrestStarPulseShotQigongParAffix,
        3: UncategorizedUniqueSkill.mountainBreakingCannon3,
        4: UncategorizedUniqueSkill.masterfulMountainBreakingCannon,
        5: UncategorizedUniqueSkill.qigongEnvelopment3,
        6: UncategorizedUniqueSkill.masterfulQigongEnvelopment,
        7: UncategorizedUniqueSkill.parRemovalDown2,
        8: UncategorizedUniqueSkill.initialQigongGain3,
        9: UncategorizedUniqueSkill.gatekeepersDuty2,
      },
      LevelGate.seventh: <int, UniqueSkill>{
        2: UncategorizedUniqueSkill.directAttackCounter3,
        3: UncategorizedUniqueSkill.mountainBreakingCannonQigongGain2,
        4: UncategorizedUniqueSkill.painToQigong3,
        5: UncategorizedUniqueSkill.jiQigongResultsTraining,
        6: UncategorizedUniqueSkill.jiQigongMuscleSolstice,
        9: UncategorizedUniqueSkill.bondsScarletDevilMansion3,
      },
      LevelGate.eighth: <int, UniqueSkill>{
        2: UncategorizedUniqueSkill.masterfulEarthMovingStarPulseShot,
        4: UncategorizedUniqueSkill.masterfulMountainBreakingCannonGuardPierce,
        5: UncategorizedUniqueSkill.jiQigongCulminationTraining,
        6: UncategorizedUniqueSkill.jiQigong2,
      },
    },
  ),
  alice(
    <Mastery>[Mastery.inorganic, Mastery.arcane, Mastery.engineering],
    <Personality>[
      Personality.perfectionist,
      Personality.creative,
      Personality.actuallyNice,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  nitori(
    <Mastery>[Mastery.engineering, Mastery.cultural, Mastery.heavy],
    <Personality>[
      Personality.cheapskate,
      Personality.diligent,
      Personality.outgoing,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  aya(
    <Mastery>[Mastery.weaponry, Mastery.bestial, Mastery.inorganic],
    <Personality>[
      Personality.speedy,
      Personality.nihilist,
      Personality.perfectionist,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  patchouli(
    <Mastery>[Mastery.arcane, Mastery.elemental, Mastery.cultural],
    <Personality>[Personality.brainy, Personality.loner, Personality.dense],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  cirno(
    <Mastery>[Mastery.vigor, Mastery.elemental, Mastery.botanical],
    <Personality>[
      Personality.prankster,
      Personality.lively,
      Personality.courageous,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  keine(
    <Mastery>[Mastery.cultural, Mastery.mythical, Mastery.protective],
    <Personality>[
      Personality.diligent,
      Personality.altruistic,
      Personality.caretaker,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  doremy(
    <Mastery>[Mastery.madness, Mastery.garment, Mastery.vigor],
    <Personality>[
      Personality.freeSpirited,
      Personality.mysterious,
      Personality.supportive,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  yukari(
    <Mastery>[Mastery.mythical, Mastery.arcane, Mastery.cultural],
    <Personality>[
      Personality.overwhelmingPresence,
      Personality.innerFacing,
      Personality.caretaker,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  marisa(
    <Mastery>[Mastery.arcane, Mastery.garment, Mastery.elemental],
    <Personality>[
      Personality.hardWorker,
      Personality.heroic,
      Personality.passionate,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  koishi(
    <Mastery>[Mastery.madness, Mastery.inorganic, Mastery.garment],
    <Personality>[
      Personality.selfReliant,
      Personality.innerFacing,
      Personality.finisher,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  sumireko(
    <Mastery>[Mastery.divine, Mastery.engineering, Mastery.cultural],
    <Personality>[
      Personality.challengeSeeker,
      Personality.courageous,
      Personality.heroic,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  ran(
    <Mastery>[Mastery.bestial, Mastery.arcane, Mastery.divine],
    <Personality>[Personality.alluring, Personality.earnest, Personality.loyal],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  chen(
    <Mastery>[Mastery.bestial, Mastery.vigor, Mastery.botanical],
    <Personality>[Personality.lively, Personality.clumsy, Personality.speedy],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  sanae(
    <Mastery>[Mastery.garment, Mastery.cultural, Mastery.engineering],
    <Personality>[
      Personality.laidback,
      Personality.supportive,
      Personality.harmonyWithNature,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  kanako(
    <Mastery>[Mastery.heavy, Mastery.engineering, Mastery.inorganic],
    <Personality>[
      Personality.divine,
      Personality.outgoing,
      Personality.overwhelmingPresence,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  suwako(
    <Mastery>[Mastery.botanical, Mastery.mythical, Mastery.garment],
    <Personality>[
      Personality.cheerful,
      Personality.airheaded,
      Personality.divine,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  remilia(
    <Mastery>[Mastery.heavy, Mastery.vigor, Mastery.mythical],
    <Personality>[
      Personality.grandiose,
      Personality.overwhelmingPresence,
      Personality.thorough,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  sakuya(
    <Mastery>[Mastery.weaponry, Mastery.inorganic, Mastery.madness],
    <Personality>[
      Personality.mysterious,
      Personality.secretlyCrazy,
      Personality.coolHeaded,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  junko(
    <Mastery>[Mastery.divine, Mastery.arcane, Mastery.bestial],
    <Personality>[
      Personality.coolHeaded,
      Personality.mysterious,
      Personality.divine,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  hecatia(
    <Mastery>[Mastery.heavy, Mastery.elemental, Mastery.madness],
    <Personality>[
      Personality.nonconformist,
      Personality.divine,
      Personality.selfReliant,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  youmu(
    <Mastery>[Mastery.weaponry, Mastery.protective, Mastery.inorganic],
    <Personality>[
      Personality.hardWorker,
      Personality.laborer,
      Personality.dense,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  rumia(
    <Mastery>[Mastery.elemental, Mastery.vigor, Mastery.garment],
    <Personality>[
      Personality.laidback,
      Personality.dense,
      Personality.airheaded,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  kogasa(
    <Mastery>[Mastery.inorganic, Mastery.botanical, Mastery.protective],
    <Personality>[
      Personality.laborer,
      Personality.sensitive,
      Personality.loyal,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  reisen(
    <Mastery>[Mastery.madness, Mastery.bestial, Mastery.divine],
    <Personality>[
      Personality.thorough,
      Personality.hardWorker,
      Personality.facilitator,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  rin(
    <Mastery>[Mastery.bestial, Mastery.weaponry, Mastery.madness],
    <Personality>[
      Personality.upfront,
      Personality.alluring,
      Personality.nihilist,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  kasen(
    <Mastery>[Mastery.botanical, Mastery.bestial, Mastery.heavy],
    <Personality>[
      Personality.caretaker,
      Personality.goodPerson,
      Personality.harmonyWithNature,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  yuugi(
    <Mastery>[Mastery.heavy, Mastery.protective, Mastery.madness],
    <Personality>[
      Personality.competitive,
      Personality.challengeSeeker,
      Personality.sturdy,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  suika(
    <Mastery>[Mastery.inorganic, Mastery.heavy, Mastery.weaponry],
    <Personality>[
      Personality.crude,
      Personality.freeSpirited,
      Personality.thorough,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  wriggle(
    <Mastery>[Mastery.botanical, Mastery.protective, Mastery.elemental],
    <Personality>[
      Personality.harmonyWithNature,
      Personality.clumsy,
      Personality.laborer,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  mystia(
    <Mastery>[Mastery.bestial, Mastery.vigor, Mastery.weaponry],
    <Personality>[
      Personality.laidback,
      Personality.cheerful,
      Personality.passionate,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  eirin(
    <Mastery>[Mastery.mythical, Mastery.divine, Mastery.weaponry],
    <Personality>[
      Personality.intellectual,
      Personality.brainy,
      Personality.coolHeaded,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  byakuren(
    <Mastery>[Mastery.arcane, Mastery.mythical, Mastery.vigor],
    <Personality>[
      Personality.altruistic,
      Personality.goodPerson,
      Personality.speedy,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  iku(
    <Mastery>[Mastery.garment, Mastery.protective, Mastery.elemental],
    <Personality>[
      Personality.supportive,
      Personality.harmonyWithNature,
      Personality.easygoing,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  momiji(
    <Mastery>[Mastery.protective, Mastery.weaponry, Mastery.bestial],
    <Personality>[Personality.loyal, Personality.earnest, Personality.diligent],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  tenshi(
    <Mastery>[Mastery.protective, Mastery.botanical, Mastery.heavy],
    <Personality>[Personality.crude, Personality.grandiose, Personality.sturdy],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  yuyuko(
    <Mastery>[Mastery.garment, Mastery.heavy, Mastery.divine],
    <Personality>[
      Personality.freeSpirited,
      Personality.prankster,
      Personality.alluring,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  mokou(
    <Mastery>[Mastery.elemental, Mastery.vigor, Mastery.mythical],
    <Personality>[
      Personality.solitary,
      Personality.challengeSeeker,
      Personality.actuallyNice,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  kokoro(
    <Mastery>[Mastery.inorganic, Mastery.weaponry, Mastery.madness],
    <Personality>[
      Personality.laidback,
      Personality.solitary,
      Personality.clumsy,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  satori(
    <Mastery>[Mastery.garment, Mastery.madness, Mastery.botanical],
    <Personality>[
      Personality.coolHeaded,
      Personality.loner,
      Personality.sensitive,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  utsuho(
    <Mastery>[Mastery.elemental, Mastery.bestial, Mastery.vigor],
    <Personality>[
      Personality.airheaded,
      Personality.cheerful,
      Personality.nonconformist,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  kaguya(
    <Mastery>[Mastery.elemental, Mastery.mythical, Mastery.cultural],
    <Personality>[
      Personality.thorough,
      Personality.nihilist,
      Personality.finisher,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  flandre(
    <Mastery>[Mastery.madness, Mastery.heavy, Mastery.arcane],
    <Personality>[
      Personality.secretlyCrazy,
      Personality.loner,
      Personality.competitive,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  sagume(
    <Mastery>[Mastery.protective, Mastery.mythical, Mastery.divine],
    <Personality>[
      Personality.soltiary,
      Personality.creative,
      Personality.mysterious,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  ),
  miko(
    <Mastery>[Mastery.mythical, Mastery.weaponry, Mastery.inorganic],
    <Personality>[
      Personality.prodigy,
      Personality.grandiose,
      Personality.nonconformist,
    ],
    <LevelGate, Map<int, UniqueSkill>>{
      LevelGate.first: <int, UniqueSkill>{},
      LevelGate.second: <int, UniqueSkill>{},
      LevelGate.third: <int, UniqueSkill>{},
      LevelGate.fourth: <int, UniqueSkill>{},
      LevelGate.fifth: <int, UniqueSkill>{},
      LevelGate.sixth: <int, UniqueSkill>{},
      LevelGate.seventh: <int, UniqueSkill>{},
      LevelGate.eighth: <int, UniqueSkill>{},
    },
  );

  /// The filename to use when reading character portraits
  String get filename => (index + 1).toString().padLeft(3, '0');

  /// The unique skills in this character's unique skill tree
  final Map<LevelGate, Map<int, UniqueSkill>> uniqueSkills;

  /// A flattened version of [uniqueSkills]
  Iterable<UniqueSkill> get flattenedUniqueSkills => uniqueSkills.values.expand(
    (Map<int, UniqueSkill> skillMap) => skillMap.values,
  );

  /// A map for additional requirements to be applied alongside the skill's
  /// requirements. Usually used by generic skills that occupy different
  /// positions in different characters's trees
  final Map<UniqueSkill, List<Skill>> additionalSkillRequirements;

  /// The masteries this character has in the training skill tree
  final List<Mastery> masteries;

  /// The personalities this character has in the training skill tree
  final List<Personality> personalities;

  const Character(
    this.masteries,
    this.personalities,
    this.uniqueSkills, {
    this.additionalSkillRequirements = const <UniqueSkill, List<Skill>>{},
  });
}
